# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b56b5b3df31abaa0b18d836e558136d1c115dec206430169fd5d8a4797ec36e5fadb476bb2948070298e4736b33a7292f62bd0cb9ef1a8f5580c83fa3c75419

test:
  secret_key_base: da2d6f727a42f4904d1acbb5a3ddcf57c0232c9a1d1e770d7a11a557326146fe9ea1ef52805ba59dd926ce4b640e98f29e5edf7bcbfab82586b4141f6dde9067

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
